Грудинин Михаил. Task №3
touge13/spbuPythonCourse pull request #2
Opened 2024-10-15 08:21 UTC by touge13

2024-10-15 12:44 UTC, Krekep requested changes
Необходимы исправления

2024-10-15 12:44 UTC, Krekep commented on project/decorators/cache_decorator.py
> +    return x + y
Это должно быть в тестах или примерах, а не в исходниках

2024-10-15 12:44 UTC, Krekep commented on project/decorators/curry.py
> +    def curried(*args):
После каррирования функция должна принимать только один аргумент. Сейчас на вход `curried` можно передать кортеж аргументов

2024-10-15 12:44 UTC, Krekep commented on project/decorators/smart_args.py
> +            pos_defaults_offset = len(positional_args) - len(defaults)
Эту информацию достаточно посчитать один раз, её можно вынести из `wrapper`

2024-10-15 12:44 UTC, Krekep commented on project/decorators/smart_args.py
> +    return d
Это должно быть в тестах или примерах, а не в исходниках

2024-10-15 12:44 UTC, Krekep commented on tasks/task1.md
Необязательно это менять в `tasks`. Достаточно того, что Вы это указываете в описании к PR

2024-10-15 12:44 UTC, Krekep commented on tests/test_decorators/test_cache_decorator.py
> +    assert expensive_computation(2) == 2  # New input, should compute
Этот тест не показывает, что кэш действительно используется. Он показывает, что два числа корректно складываются

2024-10-15 12:44 UTC, Krekep commented on tests/test_decorators/test_cache_decorator.py
> +    cached_function = cache_results(max_cache_size=2)(expensive_computation)
А разве `expensive_comptutation` уже не обёрнут в `cache_results`? 🤔

2024-10-15 12:44 UTC, Krekep commented on tests/test_decorators/test_cache_decorator.py
Тесты не демонстрирует того, что кэш действительно работает, а также удаляет последние элементы при достижении лимита вместимости. Не хватает тестов на кэширование встроенных функций

2024-10-15 12:44 UTC, Krekep commented on tests/test_decorators/test_curry.py
Не хватает теста проверяющего, что каррирование "замораживает" арность функции с произвольным числом аргументов, и теста со встроенными в Python функциями

2024-10-15 12:44 UTC, Krekep commented on project/decorators/smart_args.py
> +                    bound_args[name] = copy.deepcopy(kwargs.get(name, {}))  # Deep copy
Лучше вызвать исключение, если пользователь не указал значение для Isolated

2024-10-15 12:44 UTC, Krekep commented on tests/test_decorators/test_smart_args.py
> +    assert result["a"] == 1  # Check if the modification is successful
Этот тест продублирован выше

2024-10-15 12:44 UTC, Krekep commented on tests/test_decorators/test_smart_args.py
> +    assert result == {}  # Initial value of the dictionary should be empty
Этот тест продублирован выше

2024-10-15 12:44 UTC, Krekep commented on tests/test_decorators/test_smart_args.py
Тесты не проверяют, что Evaluated вызывается каждый раз при вызове функции, а Isolated подставляет вместо аргумента его глубокую копию

2024-10-16 12:56 UTC, touge13 commented on project/decorators/cache_decorator.py
> +    return x + y
согласен, функцию перенёс

2024-10-16 12:57 UTC, touge13 commented on project/decorators/curry.py
> +    def curried(*args):
исправлено

2024-10-16 12:58 UTC, touge13 commented on project/decorators/smart_args.py
> +            pos_defaults_offset = len(positional_args) - len(defaults)
согласен, не заметил, исправлено

2024-10-16 12:58 UTC, touge13 commented on project/decorators/smart_args.py
> +    return d
перенёс

2024-10-16 12:59 UTC, touge13 commented on tasks/task1.md
по правде сказать, мне так удобнее, но если это принципиально, то могу все исправить

2024-10-16 13:00 UTC, touge13 commented on tests/test_decorators/test_cache_decorator.py
> +    assert expensive_computation(2) == 2  # New input, should compute
согласен, очень глупо с моей стороны, исправил

2024-10-16 13:06 UTC, touge13 commented on tests/test_decorators/test_cache_decorator.py
> +    cached_function = cache_results(max_cache_size=2)(expensive_computation)
да, конечно обёрнут, исправил

2024-10-16 13:07 UTC, touge13 commented on tests/test_decorators/test_cache_decorator.py
логика исправлена, тесты в случае достижения лимита работают, тесты со встроенными функциями добавил

2024-10-16 13:20 UTC, touge13 commented on tests/test_decorators/test_curry.py
если я правильно понял про замораживание арности функции: после каррирования функция ожидает строго определённое количество аргументов, которые можно передать частями, пока все они не будут переданы или можно передать все сразу, то тесты добавил. Со встроенными функциями тесты также добавил.

2024-10-16 13:54 UTC, touge13 commented on project/decorators/smart_args.py
> +                    bound_args[name] = copy.deepcopy(kwargs.get(name, {}))  # Deep copy
согласен, добавил исключение и тест к нему. Разобрался с Isolated() и немного поработал над логикой, по условию аргумент должен быть передан, теперь это реализовано более корректно, а так же исправлены тесты

2024-10-16 13:56 UTC, touge13 commented on tests/test_decorators/test_smart_args.py
> +    assert result == {}  # Initial value of the dictionary should be empty
заметил дублирование, исправил

2024-10-16 14:14 UTC, touge13 commented on tests/test_decorators/test_smart_args.py
> +    assert result["a"] == 1  # Check if the modification is successful
поработал с тестами, дублирование убрал

2024-10-16 14:33 UTC, touge13 commented on tests/test_decorators/test_smart_args.py
согласен, добавил тесты `test_evaluated_called_each_time`, `test_isolated_returns_deep_copy`

2024-10-19 08:13 UTC, Krekep approved these changes
Зачтено

2024-10-19 08:13 UTC, Krekep commented on tests/test_decorators/test_curry.py
> +        curried_function(1)(2)
Почему `curried_function(1)(2)` должно выдавать ошибку?

2024-10-19 08:13 UTC, Krekep commented on tests/test_decorators/test_smart_args.py
> +def test_isolated():
Этот тест проверяет, что при вызове функции два раза и передачи туда вместо `d` значения, оно вернётся без изменений.
Он не проверяет, что происходит глубокое копирование переданного аргумента

2024-10-19 08:13 UTC, Krekep commented on tests/test_decorators/test_smart_args.py
> +    return d
Зачем они Вам, если Вы их не используете в тестах?

2024-10-19 09:16 UTC, touge13 commented on tests/test_decorators/test_smart_args.py
> +    return d
да, не заметил, используется только `get_random_number` , исправил

2024-10-19 09:16 UTC, touge13 commented on tests/test_decorators/test_curry.py
> +        curried_function(1)(2)
точно, ошибки не будет, исправил

2024-10-19 09:17 UTC, merged