Грудинин Михаил. Task 3
touge13/spbuPythonCourse pull request #3
Opened 2024-10-17 12:26 UTC by touge13

# Задача 3. Генераторы

* **Дедлайн**: 17.10.2024, 23:59
* Полный балл: 5

## Задача

- [x] Написать генераторное выражение для четырехмерного набора векторов [RGBA](https://en.wikipedia.org/wiki/RGBA_color_model) модели, где прозрачность принимает только чётные значения. Реализуйте функцию, возвращаю `i` элемент этого набора. Каждый цвет может принимать значения от 0 до 255 включительно, прозрачность может принимать значения от 0 до 100 включительно.
- [x] Реализовать функцию-генератор последовательности простых чисел. Обернуть её в декоратор, возвращающий `k`-е простое число (нумерация с единицы).
- [x] Добавить тесты покрывающие реализованную функциональность. Тесты должны использовать либо декоратор pytest.fixture, либо pytest.parametrize.

2024-10-19 08:25 UTC, Krekep requested changes
Необходимы исправления

2024-10-19 08:25 UTC, Krekep commented on project/generators/primes.py
> +            yield num
С одной стороны это решение работает быстрее наивного, но с другой стороны оно требует дополнительной (и не константой) памяти.
Суть этого генератора в том, что он может сгенерировать бесконечную последовательность простых чисел, но добавив в него массив, в котором хранятся найденный простые, Вы ограничили размер последовательности.
Перепишите его без использования массива с простыми числами

2024-10-19 08:25 UTC, Krekep commented on project/generators/primes.py
> +        gen = prime_generator()
Генератор не меняется, нет нужды создавать его каждый раз, особенно при условии того, что `k` на вход подаются в неубывающем порядке

2024-10-19 08:25 UTC, Krekep commented on project/generators/rgba.py
> +        for a in range(0, 101, 2)
Формально Вы правы, но перепишите с использованием `if` для демонстрации того, что Вы это умеете

2024-10-19 08:25 UTC, Krekep commented on project/generators/primes.py
> +    def wrapper(k):
Не хватает аннотаций у аргументов и функций

2024-10-20 10:58 UTC, touge13 commented on project/generators/primes.py
> +            yield num
хорошо, исправил

2024-10-20 10:58 UTC, touge13 commented on project/generators/primes.py
> +        gen = prime_generator()
согласен, исправил

2024-10-20 10:58 UTC, touge13 commented on project/generators/rgba.py
> +        for a in range(0, 101, 2)
добавил if, надеюсь правильно Вас понял

2024-10-20 10:58 UTC, touge13 commented on project/generators/primes.py
> +    def wrapper(k):
согласен, добавил

2024-10-20 11:28 UTC, Krekep approved these changes
Зачтено

2024-10-20 11:28 UTC, Krekep commented on project/generators/primes.py
> +prime_gen = prime_generator()
Кажется, это можно было объявить в функции `get_kth_prime`

2024-10-20 11:29 UTC, Krekep commented on project/generators/rgba.py
> +        for a in range(0, 101, 2)
Всегда можно уточнить у меня, правильно ли Вы поняли

2024-10-20 20:18 UTC, closed without merging