Грудинин Михаил. Task №4
touge13/spbuPythonCourse pull request #4
Opened 2024-10-20 20:13 UTC by touge13

# Задача 4. Пул потоков

* **Дедлайн**: 24.10.2024, 23:59
* Полный балл: 10

## Задача

- [x] Реализовать паттерн "пул потоков".
  - [x] Число потоков задаётся константой в классе пула или параметром конструктора.
  - [x] У каждого потока есть два состояния: ожидание задачи, выполнение задачи.
  - [x] Задача --- некая функция проводящая вычисления и возвращающая результат.
  - [x] Добавление задачи осуществляется с помощью метода `enqueue(task)`
  - [x] При добавлении задачи, если в пуле есть ожидающий поток, то он должен приступить к её выполнению. Иначе задача будет ожидать исполнения, пока не освободится какой-нибудь поток.
  - [x] Метод `dispose` должен завершать работу потоков. Уже запущенные задачи не прерываются, но новые задачи не принимаются на исполнение потоками из пула.
  - [x] Ограничения:
    - Разрешено использовать только пакет threading
    - Для каждого базового сценария должен быть написан несложный тест
    - Также должен быть написан тест, проверяющий, что в пуле действительно не менее `n` потоков
  - [ ] Допущения:
    - Использование класса для реализации пула потоков необязательно
- [x] **(Доп., +2 балла)** С помощью `concurrent.futures` реализовать параллельное вычисление суммы полного декартового произведения множества целых чисел

2024-10-21 08:42 UTC, Krekep requested changes
Необходимы исправления

2024-10-21 08:42 UTC, Krekep commented on project/thread_pool/parallel_cartesian_sum.py
> +    with concurrent.futures.ThreadPoolExecutor() as executor:
Чем обоснован выбор `ThreadPoolExecutor` для этой задачи?

2024-10-21 08:42 UTC, Krekep commented on project/thread_pool/parallel_cartesian_sum.py
> +        future = executor.submit(cartesian_product_sum, sets)
Вы отправляете одну задачу, которая будет выполняться одним потоком, нет?

2024-10-21 08:42 UTC, Krekep commented on project/thread_pool/thread_pool.py
> +                task, args, kwargs = self.tasks.pop(0)
А что будет, если несколько потоков получат сигнал из `dispose` и попробуют получить задачу?

2024-10-21 08:42 UTC, Krekep commented on tests/test_thread_pool/test_thread_pool.py
> +    assert len(pool.threads) == 3, f"Expected 3 threads, but got {len(pool.threads)}"
Лучше проверять через `threading.active_count()`

2024-10-21 08:42 UTC, Krekep commented on tests/test_thread_pool/test_thread_pool.py
> +    [(33, [{22}, {11}]), (20, [{1, 2}, {3, 4}]), (84, [{1, 2}, {3, 4}, {5, 6}])],
Почему этот тест так похож (да и в целом эта подзадача) на такой же тест у [#GigaKekes](https://github.com/GigaKekes) 🤔

2024-10-21 08:42 UTC, Krekep commented on tests/test_thread_pool/test_thread_pool.py
> +def test_parallel_cartesian_sum(expected_sum, list_of_sets):
Круто, что корректно складываются числа, но хочется ещё посмотреть на сравнительное время работы

2024-10-22 08:21 UTC, Krekep commented on tests/test_thread_pool/test_thread_pool.py
> +def test_parallel_cartesian_sum(expected_sum, list_of_sets):
Ладно, скорее всего я был неправ, давая такое задание. Для более тяжёлых функций, чем `sum` задание имело бы смысл, но в с учётом того, что `sum` использует сишную реализацию, оверхед на копирование массивов между процессами и их синхронизацию сильно больше, чем выигрыш от их использования в такой простой задаче. Так что окей, можете не добавлять такой тест. Либо можете добавить более тяжёловесную функцию (добавить, к примеру косинусы, синусы, корни или, к примеру, сортировку сделать) и показать, что с процессами она будет быстрее
Также можете почитать [этот тред](https://www.reddit.com/r/Python/comments/5tfm64/multiprocessing_parallel_sum_slower_than_serial/) и [вот этот](https://stackoverflow.com/questions/42074501/python-concurrent-futures-processpoolexecutor-performance-of-submit-vs-map)

2024-10-23 11:48 UTC, touge13 commented on project/thread_pool/parallel_cartesian_sum.py
> +    with concurrent.futures.ThreadPoolExecutor() as executor:
Изучил вопрос, действительно, лучше использовать ProcessPoolExecutor.
В случае с ThreadPoolExecutor из-за GIL (Global Interpreter Lock) потоки не могут выполнять вычисления одновременно на разных ядрах. GIL блокирует выполнение потоков на уровне интерпретатора.
Процессы в ProcessPoolExecutor имеют собственный GIL, и это позволяет использовать несколько ядер процессора, и так получается эффективнее для вычислительных задач

2024-10-23 11:48 UTC, touge13 commented on project/thread_pool/parallel_cartesian_sum.py
> +        future = executor.submit(cartesian_product_sum, sets)
Исправлено

2024-10-23 11:50 UTC, touge13 commented on project/thread_pool/thread_pool.py
> +                task, args, kwargs = self.tasks.pop(0)
несколько потоков могут одновременно достигнуть момента, когда проверяется условие if self.shutdown_flag and not self.tasks:. Если один поток получает задачу из списка self.tasks, а другой поток в это же время пытается это сделать, это может привести к IndexError, если список стал пустым после извлечения задачи одним из потоков. Исправил.

2024-10-23 11:50 UTC, touge13 commented on tests/test_thread_pool/test_thread_pool.py
> +    assert len(pool.threads) == 3, f"Expected 3 threads, but got {len(pool.threads)}"
Согласен, исправил

2024-10-23 11:50 UTC, touge13 commented on tests/test_thread_pool/test_thread_pool.py
> +    [(33, [{22}, {11}]), (20, [{1, 2}, {3, 4}]), (84, [{1, 2}, {3, 4}, {5, 6}])],
я только тест стащил, остальное даже не читал, честно 😁

2024-10-23 11:50 UTC, touge13 commented on tests/test_thread_pool/test_thread_pool.py
> +def test_parallel_cartesian_sum(expected_sum, list_of_sets):
спасибо за информацию, изучил

2024-10-24 09:15 UTC, Krekep approved these changes
Зачтено

2024-10-24 13:52 UTC, merged