Грудинин Михаил. Task №5
touge13/spbuPythonCourse pull request #5
Opened 2024-10-27 12:40 UTC by touge13

# Задача 5. Игра

* **Дедлайн**: 31.10.2024, 23:59
* Полный балл: 13

## Задача

- [ ] Реализовать одну из игр в списке ниже. Вариант определяется как длина Вашего ФИО по модулю 2 плюс 1
  1. [рулетка](https://ru.wikipedia.org/wiki/%D0%A0%D1%83%D0%BB%D0%B5%D1%82%D0%BA%D0%B0)
  2. [блэкджек](https://ru.wikipedia.org/wiki/%D0%91%D0%BB%D1%8D%D0%BA%D0%B4%D0%B6%D0%B5%D0%BA)
- Пример выбора варианта
  - len(Алимов Павел Геннадьевич) = 6 + 5 + 11 = 22
  - 22 % 2 = 0
  - 0 + 1 = 1 -> вариант 1
-------------------
  - Требования:
    - [x] Должно быть как минимум три различных стратегии игры ботов
    - [x] Должны быть методы, показывающие текущее состояние игры
    - [x] На каждую сущность должен быть свой класс
  - Ограничения:
    - [x] Игра ведётся либо до победы одного/нескольких участников, либо до заданного количества шагов
  - Допущения:
    - [x] Реализовывать Игрока необязательно. Достаточно того, что в игре будут участвовать только боты
    - [x] Графический интерфейс необязателен. Информацию достаточно выводить в консоль
  - Проверка:
    - [x] Будет проверяться декомпозиция на классы
    - [x] Тесты должны отображать
      - Что состояние игры меняется с течением времени
      - Работоспособность методов влияющих на состояние игры
      - Может быть что-то ещё, тестов много не бывает
    - [x] Надо добавить пример работы игры с выводом информации о состоянии в каждом раунде. Для примеров лучше создать отдельную папку `examples`
- [x] **(Доп., +5 балла)** Для реализованной игры построить [UML диаграмму классов](https://en.wikipedia.org/wiki/Class_diagram)
- [x] **(Доп., +5 балла)** С помощью метаклассов добавить стратегию бота и поменять правила игры (к примеру, количество полей или условия победы)

2024-10-28 09:10 UTC, Krekep requested changes
В целом всё хорошо, основные замечания к UML диаграмме

2024-10-28 09:10 UTC, Krekep commented on blackjack_class_diagram
Создайте лучше папку `docs`, в которой будет лежать необходимая по заданию документация к задачам.

2024-10-28 09:10 UTC, Krekep commented on project/game/UML.png
Вам необходимо переделать UML диаграмму классов, в текущем варианте не могу зачесть.
Некорректно отображены отношения между компонентами, некорректно оформлены описания классов. И из Вашей диаграммы похоже, что `Bot` никак не участвует в игре

2024-10-28 09:10 UTC, Krekep commented on project/game/choose_variant.ipynb
Эту информацию можно добавить в Readme

2024-10-28 09:10 UTC, Krekep commented on project/game/examples/meta_check.ipynb
Лучше отображать, что у классов поменялись атрибуты/методы, вместо запуска игры

2024-10-28 09:10 UTC, Krekep commented on project/game/src/bot.py
> +        while score <= 11 and aces:
Почему `while score <= 11`? Разве не должно быть `while score <= target_score`?

2024-10-28 09:10 UTC, Krekep commented on project/game/src/game.py
> +            self.log("Game ended due to max steps without a winner.")
Игра не должна предлагать ботам, которые уже проиграли сделать ход. В текущей редакции они делают ход, просто решают не тянуть из-за своей стратегии

2024-10-28 15:27 UTC, touge13 commented on blackjack_class_diagram
почему-то никогда раньше не использовал docs, очень полезно, спасибо!

2024-10-28 15:27 UTC, touge13 commented on project/game/UML.png
разобрался с темой, всё переделал

2024-10-28 15:27 UTC, touge13 commented on project/game/choose_variant.ipynb
хорошо, удалил choose_variant.ipynb, обновил readme.md

2024-10-28 15:27 UTC, touge13 commented on project/game/examples/meta_check.ipynb
согласен, добавил тесты

2024-10-28 15:28 UTC, touge13 commented on project/game/src/bot.py
> +        while score <= 11 and aces:
я вычитал такие правила: "Туз может считаться либо 10, либо 1: Если игрок вытягивает туза, и сумма карт на руках не превышает 21, туз считается за 10. Если же сумма карт на руках с учетом туза превышает 21, тогда туз считается за 1."

обновил правила игры в readme.md

2024-10-28 15:28 UTC, touge13 commented on project/game/src/game.py
> +            self.log("Game ended due to max steps without a winner.")
исправил

2024-10-29 18:37 UTC, Krekep requested changes
Необходимы исправления

2024-10-29 18:37 UTC, Krekep commented on project/game/docs/UML.png
По диаграмме и коду видно, что у Вас все поля и методы являются публичными, что нарушает принцип инкапсуляции, исправьте
Также на диаграмме отобразите видимость полей и методов

2024-10-29 18:37 UTC, Krekep commented on project/game/docs/UML.png
Также связь между игрой и ботами/колодой скорее композиция, чем ассоциация

2024-10-29 18:37 UTC, Krekep commented on project/game/examples/meta_examples.ipynb
Знаете, всё ещё не могу понять, что Вы хотели показать этим файлом.
В плане того, что работоспособность метаклассов вполне показывают тесты, а этот ноутбук выглядит очень не оформленным.
Без текстового объяснения происходящего, просто набор картинок
Если Вы не работали с ноутбуками, то окей, но попробуйте избавиться в нём от картинок с кодом и добавить текстовых комментариев

2024-10-29 18:37 UTC, Krekep commented on project/game/src/bot.py
> +        while score <= 11 and aces:
Да, но такое правило из-за того, что целевой счёт в игре по умолчанию --- 21. У Вас целевой счёт меняется с помощью метакласса и поэтому это правило тоже должно подвергнуться соответствующему изменению

2024-10-29 18:37 UTC, Krekep commented on project/game/src/bot.py
> +        self.hand: List["Card"] = []  # List of cards in the bot's hand
По факту у Вас две сущности --- бот и его рука, т.о. в текущем варианте класс `Bot` нарушает принцип единственной ответственности из SOLID.
Разделите класс на два

2024-10-29 18:37 UTC, Krekep commented on project/game/src/game.py
> +        bots: List,
Укажите списком чего является аргумент `bots`

2024-10-29 18:37 UTC, Krekep commented on project/game/src/bot.py
> +            attrs["decide"] = lambda self: self.calculate_score() < 19
Все эти стратегии звучат странно с учётом того, что целевой счёт может меняться. Если целевой счёт == 500, то все эти стратегии (кроме mixed) не имеют шансов на победу.

2024-10-29 18:37 UTC, Krekep commented on project/game/src/game.py
> +    def play_round(self) -> None:
Чуть не забыл самого главного --- кто же играет на интерес? В Вашем казино не хватает ставок (не забудьте, что это отдельная сущность, а значит заслуживает места на UML диаграмме классов)

2024-10-29 18:37 UTC, Krekep commented on project/game/src/game.py
> +    def play_round(self) -> None:
И замените одну из стратегий (которые по факту одинаковые, отличаются только константой) на более сложную

2024-10-31 19:57 UTC, touge13 commented on project/game/docs/UML.png
поля и методы сделал приватными, диаграмму исправил

2024-10-31 19:57 UTC, touge13 commented on project/game/examples/meta_examples.ipynb
удалил его

2024-10-31 19:58 UTC, touge13 commented on project/game/src/bot.py
> +        self.hand: List["Card"] = []  # List of cards in the bot's hand
согласен, исправил

---

"Да, но такое правило из-за того, что целевой счёт в игре по умолчанию --- 21. У Вас целевой счёт меняется с помощью метакласса и поэтому это правило тоже должно подвергнуться соответствующему изменению"

тоже исправил

2024-10-31 19:58 UTC, touge13 commented on project/game/src/game.py
> +        bots: List,
извините, это проигрыш мозга, у меня не получилось, mypy очень хочет чтобы я оставил это как есть

2024-10-31 19:58 UTC, touge13 commented on project/game/src/bot.py
> +            attrs["decide"] = lambda self: self.calculate_score() < 19
исправлено

2024-10-31 19:58 UTC, touge13 commented on project/game/src/game.py
> +    def play_round(self) -> None:
добавил баланс, ставки и тесты к ним. 

добавил более сложную стратегию и тест к ней.

2024-11-02 07:09 UTC, Krekep approved these changes
Критичных комментариев к коду нет, поэтому основная задача зачтена.
К UML диаграмме классов, замечания всё же есть, поэтому её зачесть не могу

2024-11-02 07:09 UTC, Krekep commented on blackjack_class_diagram
Этот файл не актуален, он точно нужен?

2024-11-02 07:09 UTC, Krekep commented on project/game/src/main.py
Этот файл относится к примерам использования, а не исходному коду игры. Переместите его в examples

2024-11-02 07:09 UTC, Krekep commented on project/game/docs/UML.png
1. main не нужен на данной диаграмме
2. Вы сделали слишком много методов приватными. К примеру, игра должна обладать публичным методом play, но при этом в ней могут быть приватные методы, которые пользователям этого класса не нужны, но используются внутри самой игры, к примеру, `log`
3. Между метаклассами и классами их использующими, должна быть стрелочка зависимости, а не реализации
4. Между рукой и ботом должна быть связь композиции, т.к. бот хранит в себе руку. Также и со ставкой
5. Карты должны быть связаны композицией с рукой, т.к. хранятся в ней

2024-11-02 07:09 UTC, Krekep commented on project/game/src/card.py
> +            rank (int): The rank of the card.
Использование [магических строк и чисел](https://en.wikipedia.org/wiki/Magic_number_(programming)) это антипаттерн, лучше создать перечисление/класс для хранения значений и мастей.
Т.к. эта ошибка у Вас уже третью попытку сдачи, но я не указывал до этого момента на неё, то можете считать, что это просто комментарий, а не замечаний

2024-11-02 07:09 UTC, Krekep commented on project/game/src/game.py
> +        bots: List,
О_о

2024-11-02 07:18 UTC, touge13 commented on blackjack_class_diagram
удалил, не заметил

2024-11-02 07:19 UTC, touge13 commented on project/game/src/main.py
переместил

2024-11-02 07:31 UTC, touge13 commented on project/game/docs/UML.png
1, 3, 4, 5 пункты исправлены

2024-11-02 07:36 UTC, merged